<?php

use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Drupal\commerce_payment_iyzico\PluginForm\Offsite\IyzipayBootstrap;


/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_payment_iyzico_commerce_payment_method_info() {
  $payment_methods = array();

  $payment_methods['commerce_payment_iyzico'] = array(
    'title' => t('Kredi/Banka Kartı'),
    'description' => t('Iyzico Ödeme Formu'),
    'active' => TRUE,
  );

  return $payment_methods;
}